baseURL = 'https://borocode.github.io/'
DefaultContentLanguage = "en"
languageCode = "en"
title = 'blog'
theme = "sk3"
copyright = "VIRAL PUBLIC LICENSE Copyleft (É”) All Rights Reversed"
summaryLength = 50
enableGitInfo          = true
enableInlineShortcodes = true
paginate               = 12
relativeURLs           = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 15

  [[menu.main]]
    identifier = "stats"
    name = "Stats"
    url = "/stats/"
    weight = 5

      [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

    
[Params]
enableExternalSvg    = true
enableInfoBox        = true
enableListLastModify = false
enableOpenToc        = true
enableUserCanonical  = false
favicon              = "/favicon.ico"
mainSections         = "posts"
startdate            = "2022-08-13"
pagewidth            = "3000px"

	[Params.card]
	date    = true
	summary = true
   width = "24%"

   [Params.color]
   border = "#39ff14"
   link = "white"
   bg = "black"
   text = "white"
   
	[Params.sociallink]
  youtubeuser    = "rishard"
	github         = "borocode"
	rss            = true
  discord = "QRuHnxQWb4"
  twitch = "borokhela"
  flickr = "rishadphoto"
  instagram = "boroghor"
  facebook = "rishadh"
	