baseURL = 'http://boroghor.com/'
languageCode = 'en-us'
title = 'blog'
theme = "sk3"
copyright = "VIRAL PUBLIC LICENSE Copyleft (É”) All Rights Reversed"

enableGitInfo          = true
enableInlineShortcodes = true
paginate               = 12
relativeURLs           = true
summaryLength = 10
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "stats"
    name = "Stats"
    url = "/stats/"
    weight = 10

    
[Params]
# enableExternalSvg    = true
enableInfoBox        = true
enableListLastModify = false
enableOpenToc        = true
enableUserCanonical  = false
favicon              = "/favicon.ico"
mainSections         = "posts"
startdate            = "2022-08-13"
pagewidth            = "3000px"
	[Params.card]
	date    = true
	summary = true
   width = "24%"